version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ai-service/Dockerfile.backend
    container_name: ai-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ai-service/Dockerfile.frontend
    container_name: ai-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
