apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: smart-talent-matcher-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501 # <-- change from 80 to 8501
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8501 # <-- service port
      targetPort: 8501 # <-- must match containerPort
      nodePort: 32520 # optional, fixed NodePort
  type: NodePort # <-- change LoadBalancer to NodePort for Docker Desktop
